### ISSUE TITLE
Keyword search is broken

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/legumemine#12]
whenever is most appropriate. I won't be relying on them for what I'm doing

**Comment by sammyjava** [comment]
The Lucene indexes were built. Lucene seems to be broken.

**Comment by sammyjava** [comment]
I don't think there's much I can do on this, other than maybe discover some stuff that's being indexed that shouldn't be. It takes forever on dev, and that's faster than production. We'll keep pondering.

**Comment by sammyjava** [comment]
Well, here's one reason, probably amongst others:
```
20-Dec-2017 15:57:32.845 SEVERE [ajp-apr-8009-exec-232] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [action] in context with path [/legumemine] threw exception [javax.servlet.ServletException: java.lang.OutOfMemoryError: Java heap space] with root cause
 java.lang.OutOfMemoryError: Java heap space
```
I'll boost the RAM on shokin-webapps.

**Comment by sammyjava** [comment]
So this seems to be solved. I had somehow neglected to omit Homologue and ExpressionValue from Lucene indexing, which made the indexing take forever and the search take forever. Blocking those two classes, plus a bunch of smaller ones, brought indexing down to 15m on production and searches seem to respond pretty quickly now.

It was mainly Homologue bloat from adding all the new organisms, with a touch of expression bloat from the additional expression sets.

**Comment by adf-ncgr** [comment]
much improved! no more naptime for @jd-campbell :)
