### ISSUE TITLE
pigeonpea protein DB Identifiers are chado.uniquenames

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/legumemine#14]
e.g. https://intermine.legumefederation.org/legumemine/report.do?id=13771249 =>  
cajca.ICPL87119.gnm1.ann1.C.cajan_11719.1

looks like the other species are OK in this regard. not a big deal, just happened to notice.

**Comment by sammyjava** [comment]
Oh. Yeah I hadn't taken into account changes in the new chado. Fixed in next update.
