### ISSUE TITLE
regions page has some missing parts (including the form submission buttons)

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/legumemine#18]
https://intermine.legumefederation.org/legumemine/genomicRegionSearch.do
parts 2 and 5 are blank and the Reset/Search buttons do not appear.
looks like https://mines.legumeinfo.org/peanutmine/genomicRegionSearch.do has
the same problem, though other species-specific mines seem fine.

**Comment by sammyjava** [comment]
Fixed. Somehow managed to drop this informative little blurb that comes down with new mines these days. I'll check all the mines.
```
# if enableStrandSpecificSearch is true then the mine's resources/struts-config-form-model.xml must have the entry
# <form-bean name="genomicRegionSearchForm" type="org.intermine.bio.web.struts.GenomicRegionSearchForm">
#    ...
#    <form-property name="strandSpecific" type="java.lang.Boolean"/>
# </form-bean>
genomicRegionSearch.enableStrandSpecificSearch=true
```
