### ISSUE TITLE
problem with redirection URL

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/legumemine#21]
ran into this from links on the LIS site to the "older" location of legumemine; I can fix the links to point to the "newer" location, but in case there are any I miss or don't have control over, here is the problem in a nutshell (or pod)...

> curl https://intermine.legumefederation.org/legumemine
...
<title>301 Moved Permanently</title>
href="https://mines.legumeinfo.org/**_legumeminelegumemine_**"

**Comment by sammyjava** [comment]
Yeah I can't figure out where that legumeminelegumemine thing is coming from. I've tried all sorts of combinations of the Redirect call(s) and it keeps on happening.

**Comment by adf-ncgr** [comment]
I know longer know what this was about, or seem to care. closing
