### ISSUE TITLE
Add template tabs back to home page

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/legumemine#23]
Restore the stock tabs that display categories templates to the home page. Along with, of course, building templates so they are not empty!

**Comment by sammyjava** [comment]
==========
GENOMICS
- [ ]  Region ==> Sequence
- [x] Region ==> Contained genes
- [x] Region ==> Contained markers
- [ ] Region ==> Contained GWAS features
==========
GENE PRODUCTS
- [x] Genes ==> CDS sequence
- [x] Genes ==> Protein sequence 
- [ ] Genes ==> Noncoding RNA
- [ ] Genes ==> Protein-coding genes
- [ ] Genes ==> Transposable elements
==========
COMPARISON
- [x] Genes ==> Homologs
- [ ] Region ==> Syntenic region
==========
FUNCTION
- [x]  GO term ==> Genes
- [x] Genes ==> GO terms
- [x] Functional descriptor ==> Genes
- [ ] Keyword ==> GO terms and Genes
- [ ] Genes ==> Functional Annotations

==========
EXPRESSION
- [x] Expression ==> Genes
- [x] Genes ==> RNA-seq Expression

==========
GENETICS
- [x] Trait (TO Term) ==> QTLs

==========
PUBLICATIONS
- [x] Name ==> Publication
- [x] Keyword ==> Publication

**Comment by adf-ncgr** [comment]
looks like this is done enough, but one thing I noticed is that the default term for 
Trait (TO Term) ==> QTLs 
is returning no results; I don't think I can edit it, maybe you could choose a better example and close the issue?

**Comment by sammyjava** [comment]
It's Phenotype --> QTLs now, and it's been created.
