### ISSUE TITLE
The display of list info for pathways in legumemine is hard to understand

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/legumemine#28]
In soymine, pathways come with IDs and organisms in their list displays, which would be more essential in the legumemine context, but is missing here (soymine appears to be the only mine that currently displays anything more than just the Pathway Name in list displays- they probably all should but I'd settle for legumemine at this point)

**Comment by adf-ncgr** [comment]
@sammyjava would this be a good starter issue for someone wanting to learn how to contribute to mine maintenance/customization?

**Comment by sammyjava** [comment]
Not really -- the main table on the list pages is just set by a config file. Nothing really there there. Although I don't really understand this issue, it just seems to be a statement. But it's trivial to change what's shown on the list table.

**Comment by adf-ncgr** [comment]
OK, here's the imperative form: add organism to pathway list display in legumemine.

**Comment by sammyjava** [comment]
AH! Will do. :)

**Comment by sammyjava** [comment]
This request is now rendered inappropriate since pathways are now common to all organisms (I removed the -PHV-, etc.) so we can see ALL the genes/proteins associated with a given pathway.
