### ISSUE TITLE
is the BLAST option supposed to do anything?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/legumemine#29]
besides give an error, I mean:
https://mines.legumeinfo.org/legumemine/sequenceBlaster.do?object=8797987

I imagine this isn't a very new thing. I see soymine's actually does direct people over to the "regular" LIS BLAST, so maybe it really is supposed to work.

**Comment by sammyjava** [comment]
Yeah, it's supposed to populate a form that you submit to LIS BLAST. I'll check on all the mines.

**Comment by adf-ncgr** [comment]
question: would it be possible to add other "submit sequence to form" options? would be nifty to be able to direct people over to the lorax path that begins here:
https://legumeinfo.org/annot

of course, I'd probably have to actually get this to accept a sequence via a form rather than just file upload as is currently implemented. In which case I'd probably pursue (or have someone pursue) my dream of getting to lorax a bit more directly instead. But before I issue any decrees, I'll wait for you to tell me whether adding new stylized buttons for such functions is actually something that can be done (with minimal effort on your part).

**Comment by sammyjava** [comment]
Well it says it's going to BLAST the sequence. So if you want another option, that should actually be coded as a new "exporter" and a little tiny button added to the sequence feature page alongside "FASTA" and "BLAST", say "LORAX". Which I'm happy to code up. Probably with a huge mouseover explanation of what Lorax is.

**Comment by adf-ncgr** [comment]
yeah, I didn't mean we should overload the meaning of BLAST. and don't code anything up just yet, but I'll try to learn a little more about this "exporter" business first. Presumably this is a good starting point: https://intermine.readthedocs.io/en/latest/webapp/properties/webconfig-model/#export-configuration

this issue shall hereby be about simply fixing the BLAST and we'll let exporter-exploration be another thing for later...

**Comment by sammyjava** [comment]
This is fixed on all the mines on which it was broken. I had moved my code to org.ncgr.intermine... (rather than org.intermine) but hadn't updated the struts-config-model.xml file on those mines (which differs from mine to mine depending on which displayers/widgets it provides).
