### ISSUE TITLE
Add other genomic-info species from LIS that aren't currently in mines

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/legumemine#3]
Cajanus cajan_ICPL87119
Vigna angularis_Gyeongwon
Vigna radiata_VC1973A
Trifolium pratense_MilvusB
Medicago trancatula_A17
Lupinus angustifolius_Tanjil
Lotus japonicus_MG20

**Comment by adf-ncgr** [comment]
Medicago trancatula_Mt4.0 (or is already there?)

not sure what the parenthetical question is asking, but FWIW this should be Medicago truncatula_A17 to be consistent with the use of "germplasm accession" rather than "version" naming

**Comment by adf-ncgr** [comment]
Also, just noticed that you are missing pigeonpea from your list above:
Cajanus cajan_ICPL87119

we MAY want to create a separate PigeonpeaMine in honor of my embassy to ICRISAT in Dec.

**Comment by sammyjava** [comment]
Duly updated. I need to back-edit the Mt imports on other mines, no idea why I used Mt4.0 rather than the variety.

**Comment by adf-ncgr** [comment]
@agnespychan @vivekkrish @joannmudge @cdtown with respect to medicago naming, we will at some point need to think about how to deal with cases where the accession has both a "regular name" like A17 or R108 as well as a HapMap designation like HM341 or HM340. In some of the experiments I've done I've just made a composite name like A17_HM341 but that may be more confusing to people than helpful. I would guess that many of the hapmap accessions have nothing but an HM number, though I don't know this for sure (I just know I've never heard anyone use "regular names" for more than a handful)

**Comment by joannmudge** [comment]
They all have an HM number and a population. Many of them also have a line number.

http://www.medicagohapmap.org/hapmap/germplasm <http://www.medicagohapmap.org/hapmap/germplasm>

Joann Mudge
Senior Research Scientist
National Center for Genome Resources (NCGR)
Santa Fe, NM
505-995-4421
jm@ncgr.org
Google Scholar Page <http://scholar.google.com/citations?user=Lq1fuVUAAAAJ&hl=en>

**Comment by adf-ncgr** [comment]
@ctcncgr someday that germplasm table will be interactive and tell us all about the data available for each of those lines...
