### ISSUE TITLE
genes (etc) on supercontigs not given locations?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/legumemine#31]
Sven noticed that some of the genes in legumemine aren't returning sequence when asked. For example 
https://mines.legumeinfo.org/legumemine/portal.do?class=Gene&externalids=gene16536

My theory is that there is some prejudicial treatment against non-chromosomal features at work here.

**Comment by adf-ncgr** [comment]
leaving open as it still seems to be an issue, see, e.g.:
https://mines.legumeinfo.org/soymine/portal.do?class=Gene&externalids=Glyma.U000200

**Comment by sammyjava** [comment]
I think this was a loading bug with the chado loader; I don't believe it persists now with the lis-bio-sources loaders. At least it's not the case with LupinMine. I'm going to close this since I'm not working on chado loaders any longer.
