### ISSUE TITLE
Gm chromosomes got loaded by marker file w/o organism

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/legumemine#5]
Dupe Gm chromosomes from loading these and others:
```
Sct_195 | Gm03 | 323557 | 323578 | 1
Sat_379 | Gm03 | 461901 | 461920 | 1
Satt631 | Gm03 | 2943932 | 2943979 | 1
Satt159 | Gm03 | 3197998 | 3198039 | 1
```

**Comment by adf-ncgr** [comment]
probably from marker genomic position gff downloaded from browser.

**Comment by sammyjava** [comment]
Yeah, just forgot to add the extra info (TaxonID,Variety) at the top that I've added to the file loaders one by one so the chroms 
merge properly.

**Comment by sammyjava** [comment]
Fixed. Double check after new load.

**Comment by sammyjava** [comment]
Fixed. 155 total chromosomes is correct.
